### ISSUE TITLE
Tables for research letter

### ISSUE THREAD

**Issue by tdbennett** [CUD2V/pccc#15]
@jamesfeinstein, here are the hand sketches of tables from our meeting 5/18

[TableSketch.pdf](https://github.com/dewittpe/pccc/files/1019059/TableSketch.pdf)

**Comment by tdbennett** [comment]
primary outcome for table 2: % correctly classified (accuracy)

**Comment by dewittpe** [comment]
Tables would look like this in print.

# Table 1

|                     | SAS | R   |Ratio  |
|:--------------------|:---:|:---:|:-----:|
|*Category*           |     |     |       |
|&nbsp;&nbsp;Neuromusc| xx% | yy% | yy/xx |
|&nbsp;&nbsp;CVD      | xx% | yy% | yy/xx |
|&nbsp;&nbsp;Resp     | xx% | yy% | yy/xx |
|*Time To Compute*    |     |     |       |
|&nbsp;&nbsp;NEDS     | tt  | ss  | ss/rr |
|&nbsp;&nbsp;KIDS     | tt  | ss  | ss/rr |

# Table 2a: KID 
agree/disagree table, could be for all CCC or just for one.

|      | SAS Yes | SAS No |
|:-----|:-------:|:------:|
|**R Yes** |         |        |
|**R No**  |         |        |


# Table 2b: NEDS
Same as Table 2a, but for the NEDS data instead of the KID data.

|      | SAS Yes | SAS No |
|:-----|:-------:|:------:|
|**R Yes** |         |        |
|**R No**  |         |        |

**Comment by tdbennett** [comment]
1. If 2-sigfig percentages are the same for R, SAS, Stata, will remove that table.
2. @jamesfeinstein to generate new table with columns (names are placeholders, edit as you see fit):
- "type of change/error"
- "codes changed"

3. example change types: substring error, duplicates, etc.

**Comment by tdbennett** [comment]
@jamesfeinstein has prepped these tables in the manuscript and will input the final 1) code changes and 2) timing data.

**Comment by magic-lantern** [comment]
Final version of tables included in research letter.
