### ISSUE TITLE
`pccc-overview` vignette

### ISSUE THREAD

**Issue by tdbennett** [CUD2V/pccc#31]
Hi @magic-lantern and @jamesfeinstein,

Something isn't clear about this section of the overview vignette:

```
* All codes in all categories employ "starts with substring" matching logic. Because of this, if a code to be evaluated starts with a code listed in one of the CCC categories, a match will be found. This means that if a bad ICD code is provided (such as ICD-9-CM code 0492,25042) PCCC would indicate a match for the Neuromuscular CCC.
```

How are those codes "bad?" 0492 is used in an example above that section in a way that makes it seem acceptable.

I'll push up some text edits to a few files shortly.

**Comment by magic-lantern** [comment]
What I meant here was that if someone fails to parse their file correctly, they might end up with a single “code” that is the string “0492,25042” and since anything that starts with a valid code will be treated as valid it could be an error.

Would something like “049225042” be better to illustrate this example?

**Comment by magic-lantern** [comment]
Updated text to be more clear.

Any other issues with this vignette, or shall we close this issue?

**Comment by tdbennett** [comment]
I agree, closing this issue. Can re-open if needed.
